---
title: "Extreme values statistics tools"
---

Theses tools are available through R using:

  * `install.packages('...')` for CRAN packages (Renext, SpatialExtremes, ...),
  * `devtools::install_github('IRSN/...')` (Windows: assuming devtools & Rtools are available on your system)
  * `install.packages('https://github.com/IRSN/.../releases/download/....tgz|zip|tar.gz', repos=NULL, type='binary')` (precompiled for Linux (x86), Windows, or MacOSX)
  

| Name | Short description | Location | Supports unsteady data | Processing historical data | Sampling type | Distribution laws | Confidence interval type | Covariables | Censored data | Data types | Other tool features |
| :--- | :------------------- | :--- | :--- | :--- | :--- | :--- | :--- | :------------- |
| Renext | Statistical tool for estimating extreme values in a frequentist framework with many methods | CRAN + [IRSN GitHub](https://github.com/IRSN/Renext) | <span style="color:red">✘</span>| <span style="color:green">✔</span> | POT block maxima r-LOS | GPD, expo, GEV, gumbel, mixed expo, log normal, Weibull, gamma (any with given parameters) | <span style="color:red">✘</span> | <span style="color:green">✔</span> | events, yearly, struct. | Delta | Various anova statistical tests |
| NSGEV | Statistical tool for estimating extreme values in an unsteady frequentist framework based on annual maxima | [IRSN GitHub](https://github.com/IRSN/NSGEV) | <span style="color:green">✔</span> | <span style="color:red">✘</span>| maximum block | GEV, gumbel | x(t) | <span style="color:red">✘</span> | yearly | Delta Likelihood Profile Bootstrap | Various anova statistical tests |
| potomax | Statistical tool for estimating extreme values with a new sampling method (MA censoring threshold) | [IRSN GitHub](https://github.com/IRSN/potomax) | <span style="color:red">✘</span>| <span style="color:green">✔</span> | POT block maximum | GPD, expo, GEV, gumbel | <span style="color:red">✘</span> | <span style="color:green">✔</span> | events, yearly, struct. | Delta Likelihood Profile | Validation method to check the convergence of results (argument check=TRUE) |
| SpatialExtremes | Fork of the CRAN package by Mathieu Ribatet. Modification of the package by Yves Deville, in particular of the spatgev class in order to take into account temporal covariates (possibility of using this class with NSGEV) | [Y. Deville GitHub](https://github.com/yvesdeville/SpatialExtremes) | <span style="color:green">✔</span> (using it with NSGEV) | <span style="color:red">✘</span>| maximum block | GEV, gumbel | | | | Delta Likelihood Profile Bootstrap | Package to extrapolate temperatures in places where there is data (spatial covariates) |
| bever | Statistical tool for estimating extreme values in a Bayesian framework (with focus on Markov chain Monte-Carlo) | [IRSN GitHub](https://github.com/IRSN/bever) | <span style="color:red">✘</span>| <span style="color:green">✔</span> | POT block maximum | GPD, expo, GEV, gumbel | <span style="color:red">✘</span> | <span style="color:red">✘</span> | events, yearly | Credibility intervals with HPD and equal tails methods | Calculation of the predictive distribution |
| beverstan | Rstan statistical tool, dependent on NSGEV and bever, for the estimation of extreme values in a Bayesian framework | [IRSN GitHub](https://github.com/IRSN/beverstan) | <span style="color:green">✔</span> | <span style="color:green">✔</span> | maximum block | GEV, gumbel | x(t) | <span style="color:green">✔</span> | yearly | Credibility intervals with HPD and equal tails methods | |
| dailymet | Tool for analyzing daily weather series (mainly temperatures) using POT methods | [IRSN GitHub](https://github.com/IRSN/dailymet) | <span style="color:green">✔</span> | <span style="color:red">✘</span>| POT | GPD, exhibition | x(t), x | <span style="color:red">✘</span> | daily | | Functions to describe seasonality and annual trend |
| SeaLev | Estimation of extreme sea levels by combining tide and surge | [IRSN GitHub](https://github.com/IRSN/SeaLev) | <span style="color:red">✘</span>| <span style="color:green">✔</span> (with Renext) | POT or maximum block (premiums) | Renext laws | <span style="color:red">✘</span> | <span style="color:red">✘</span> | tidely | Delta | Theoretical tide distribution |

