---
title: "Flooding simulations"
---

2D Hydro simulations environment:

* __Telemac2D docker image__ `docker run -v `echo $PWD`:/workdir irsn/telemac-mascaret:latest telemac2d.py --ncsize=10 input.cas`
* __[Funz](https://funz.github.io)-Telemac__ for parametric studies:
  * Python: `pip install Funz`, then `import Funz`, `Funz.installModel('Telemac')`
  * R: `remotes::install_github('Funz/Funz.R'); libary(Funz); Funz::installModel('Telemac')`
  * bash/cmd.exe: [Standalone dist](https://github.com/Funz/plugin-Telemac/releases/latest)


Related references :

* [Uncertainty and Sensitivity Analyses with Dépendent Inputs in a 2D Hydraulic Model of the Loire River](https://hal.science/irsn-03925235v1)
* [Inversion Algorithm for Civil Flood Defense Optimization: Application to Two-Dimensional Numerical Model of the Garonne River in France](https://www.frontiersin.org/articles/10.3389/fenvs.2019.00160/full)
* [Comparison Between HEC-RAS and TELEMAC-2D Hydrodynamic Models of the Loire River, Integrating Levee Breaches](https://easychair.org/publications/preprint_open/T21X)
* [Comparative Analysis of 1D and 2D Tools for the Modelling of the Dispersion of Liquid Discharges in Rivers](https://easychair.org/publications/preprint/8L2Z)
